SELECT RD.READER_ID, RD. FIRSTNAME, RD.LASTNAME, BK.TITLE, RT.RENT_DATE, RT.RETURN_DATE
FROM READERS RD, BOOKS BK, RENTS RT
WHERE RT.BOOK_ID = BK.BOOK_ID
AND RT.READER_ID = RD.READER_ID
ORDER BY RT.RENT_DATE;

CREATE VIEW BOOKS_AND_READERS AS
SELECT RD.READER_ID, RD. FIRSTNAME, RD.LASTNAME, BK.TITLE, RT.RENT_DATE, RT.RETURN_DATE
FROM READERS RD, BOOKS BK, RENTS RT
WHERE RT.BOOK_ID = BK.BOOK_ID
AND RT.READER_ID = RD.READER_ID
ORDER BY RT.RENT_DATE;

SELECT * FROM BOOKS_AND_READERS
WHERE RENT_DATE >= CURDATE() -35
ORDER BY LASTNAME;