DROP PROCEDURE IF EXISTS UpdateVipLevels;

DELIMITER $$

CREATE PROCEDURE UpdateVipLevels()
BEGIN
	DECLARE BOOKSREAD, DAYS, RDR_ID INT;
    DECLARE BOOKSPERMONTH DECIMAL(5,2);
    DECLARE FINISHED INT DEFAULT 0;
    DECLARE ALL_READERS CURSOR FOR SELECT READER_ID FROM READERS;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
    OPEN ALL_READERS;
    WHILE (FINISHED = 0) DO
		FETCH ALL_READERS INTO RDR_ID;
        IF (FINISHED = 0) THEN
			SELECT COUNT(*) FROM RENTS
			WHERE READER_ID = RDR_ID
			INTO BOOKSREAD;
			SELECT DATEDIFF(MAX(RENT_DATE), MIN(RENT_DATE)) FROM RENTS
			WHERE READER_ID = RDR_ID
			INTO DAYS;
			SET BOOKSPERMONTH = BOOKSREAD / DAYS * 30;
			UPDATE READERS SET VIP_LEVEL = VipLevel(BOOKSPERMONTH)
            WHERE READER_ID = RDR_ID;
			COMMIT;
		END IF;
	END WHILE;
    CLOSE ALL_READERS;
END $$

DELIMITER ;

Call UpdateVipLevels();