SET GLOBAL event_scheduler = ON;

USE KODILLA_COURSE;

CREATE TABLE STATS 
(
	STAT_ID 	INT(11) AUTO_INCREMENT PRIMARY KEY,
	STAT_DATE 	DATETIME NOT NULL,
	STAT 		VARCHAR(20) NOT NULL,
	VALUE INT(11) NOT NULL
);

SELECT * FROM STATS;

CREATE VIEW BESTSELLERS_COUNT AS 
SELECT COUNT(*) AS BESTSELLERS
FROM BOOKS
WHERE BESTSELLER = 1;

DROP VIEW BESTSELLERS_COUNT;

COMMIT;

INSERT INTO STATS (STAT_DATE, STAT, VALUE) VALUES (CURRENT_TIMESTAMP, "Bestsellers", (SELECT * FROM BESTSELLERS_COUNT));

SELECT * FROM kodilla_course.bestsellers_count;

delimiter |

CREATE EVENT UPDATE_BESTSELLERS_COUNT
	ON SCHEDULE EVERY 1 MINUTE
    DO 
		BEGIN
			CALL UpdateBestsellers();
			INSERT INTO STATS (STAT_DATE, STAT, VALUE) VALUES (CURRENT_TIMESTAMP, "Bestsellers", (SELECT * FROM BESTSELLERS_COUNT));
            COMMIT;
		END |
        
delimiter ;

DROP EVENT UPDATE_BESTSELLERS_COUNT;

COMMIT;

SELECT * FROM kodilla_course.stats;

SELECT * FROM kodilla_course.bestsellers_count;

SHOW EVENTS;
