SELECT * FROM BOOKS;

SELECT * FROM READERS;

EXPLAIN SELECT COUNT(*)
FROM BOOKS
WHERE TITLE = 'The Stranger';

CREATE INDEX TITLEON ON BOOKS (TITLE);

EXPLAIN SELECT COUNT(*)
FROM READERS
WHERE FIRSTNAME = 'John';

CREATE INDEX FIRSTNAMEON ON READERS (FIRSTNAME);

EXPLAIN SELECT COUNT(*)
FROM READERS
WHERE LASTNAME = 'Wilson';

CREATE INDEX LASTNAMEON ON READERS (LASTNAME);

